import { BarChart3, FileText, ReceiptText, UserRound, WalletCards } from 'lucide-react';
import { TabbedModulePage } from '../../core/components/TabbedModulePage';

export function AccountingPage() {
  return (
    <TabbedModulePage
      tabs={[
        {
          key: 'types',
          label: 'Loại thu chi',
          title: 'Loại phiếu thu chi',
          subtitle: 'Loại phiếu kế toán dùng cho thu, chi và kết quả kinh doanh',
          endpoint: '/accounting/types',
          icon: <WalletCards size={24} />,
          primaryActionLabel: 'Thêm loại phiếu',
          fields: [{ key: 'name', label: 'Tên loại phiếu' }, { key: 'kind', label: 'Loại', type: 'status' }, { key: 'description', label: 'Mô tả' }],
          formFields: [
            { key: 'name', label: 'Tên loại phiếu', required: true },
            { key: 'kind', label: 'Loại', type: 'select', options: [{ label: 'Phiếu thu', value: 'receipt' }, { label: 'Phiếu chi', value: 'payment' }] },
            { key: 'description', label: 'Mô tả', type: 'textarea' },
          ],
          createDefaults: { name: '', kind: 'receipt', description: '' },
          quickFilters: [{ label: 'Phiếu thu', value: 'receipt' }, { label: 'Phiếu chi', value: 'payment' }],
        },
        {
          key: 'receipts',
          label: 'Phiếu thu',
          title: 'Phiếu thu',
          subtitle: 'Quản lý khoản thu, liên kết khách hàng hoặc chứng từ bán',
          endpoint: '/accounting/receipts',
          icon: <ReceiptText size={24} />,
          primaryActionLabel: 'Tạo phiếu thu',
          fields: [{ key: 'code', label: 'Mã phiếu' }, { key: 'date', label: 'Ngày', type: 'date' }, { key: 'value', label: 'Giá trị', type: 'money' }, { key: 'businessResult', label: 'KQKD', type: 'status' }],
          formFields: [
            { key: 'code', label: 'Mã phiếu', required: true },
            { key: 'date', label: 'Ngày', type: 'date' },
            { key: 'typeId', label: 'ID loại phiếu' },
            { key: 'customerId', label: 'ID khách hàng' },
            { key: 'value', label: 'Giá trị', type: 'number' },
            { key: 'financeType', label: 'Loại chứng từ' },
            { key: 'financeId', label: 'ID chứng từ' },
            { key: 'note', label: 'Ghi chú', type: 'textarea' },
          ],
          createDefaults: { code: '', date: '', typeId: '', customerId: '', value: 0, financeType: '', financeId: '', note: '' },
        },
        {
          key: 'payments',
          label: 'Phiếu chi',
          title: 'Phiếu chi',
          subtitle: 'Quản lý khoản chi và người nhận chi',
          endpoint: '/accounting/payments',
          icon: <WalletCards size={24} />,
          primaryActionLabel: 'Tạo phiếu chi',
          fields: [{ key: 'code', label: 'Mã phiếu' }, { key: 'date', label: 'Ngày', type: 'date' }, { key: 'value', label: 'Giá trị', type: 'money' }, { key: 'businessResult', label: 'KQKD', type: 'status' }],
          formFields: [
            { key: 'code', label: 'Mã phiếu', required: true },
            { key: 'date', label: 'Ngày', type: 'date' },
            { key: 'typeId', label: 'ID loại phiếu' },
            { key: 'payPersonId', label: 'ID người nhận' },
            { key: 'value', label: 'Giá trị', type: 'number' },
            { key: 'financeType', label: 'Loại chứng từ' },
            { key: 'financeId', label: 'ID chứng từ' },
            { key: 'note', label: 'Ghi chú', type: 'textarea' },
          ],
          createDefaults: { code: '', date: '', typeId: '', payPersonId: '', value: 0, financeType: '', financeId: '', note: '' },
        },
        {
          key: 'pay-persons',
          label: 'Người nhận chi',
          title: 'Người nhận chi',
          subtitle: 'Danh bạ người nhận chi theo Polirium accounting pay person',
          endpoint: '/accounting/pay-persons',
          icon: <UserRound size={24} />,
          primaryActionLabel: 'Thêm người nhận',
          fields: [{ key: 'name', label: 'Tên' }, { key: 'phone', label: 'SĐT' }, { key: 'email', label: 'Email' }, { key: 'address', label: 'Địa chỉ' }],
          formFields: [{ key: 'name', label: 'Tên', required: true }, { key: 'phone', label: 'SĐT' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'address', label: 'Địa chỉ' }, { key: 'note', label: 'Ghi chú', type: 'textarea' }],
          createDefaults: { name: '', phone: '', email: '', address: '', note: '' },
        },
        {
          key: 'invoices',
          label: 'Hóa đơn bán',
          title: 'Hóa đơn bán',
          subtitle: 'Danh sách đơn bán hoàn tất để xuất/copy hóa đơn',
          endpoint: '/accounting/invoices',
          icon: <FileText size={24} />,
          primaryActionLabel: 'Tạo ghi chú hóa đơn',
          fields: [{ key: 'code', label: 'Mã đơn' }, { key: 'status', label: 'Trạng thái', type: 'status' }, { key: 'value', label: 'Tổng tiền', type: 'money' }, { key: 'valuePayment', label: 'Đã thu', type: 'money' }],
          formFields: [{ key: 'code', label: 'Mã đơn', required: true }, { key: 'note', label: 'Ghi chú', type: 'textarea' }],
          createDefaults: { code: '', note: '' },
        },
        {
          key: 'sales-report',
          label: 'Báo cáo bán',
          title: 'Báo cáo bán hàng',
          subtitle: 'Doanh thu, đã thu, công nợ và lãi gộp từ đơn hoàn tất',
          endpoint: '/accounting/reports/sales',
          icon: <BarChart3 size={24} />,
          primaryActionLabel: 'Tạo dòng báo cáo',
          fields: [{ key: 'code', label: 'Mã đơn' }, { key: 'status', label: 'Trạng thái', type: 'status' }, { key: 'value', label: 'Doanh thu', type: 'money' }, { key: 'totalCost', label: 'Giá vốn', type: 'money' }],
          formFields: [{ key: 'code', label: 'Mã đơn', required: true }],
          createDefaults: { code: '' },
        },
      ]}
    />
  );
}
