export const megaMenuGroups = [
  {
    title: 'Báo cáo & Thống kê',
    items: [
      { text: 'Theo thời gian', href: '/report/revenue/index?businessId=122623' },
      { text: 'Theo cửa hàng', href: '/report/revenue/depot?businessId=122623' },
      { text: 'Theo thương hiệu', href: '/report/revenue/brand?businessId=122623' },
      { text: 'Theo nhân viên', href: '/report/revenue/staff?businessId=122623' },
      { text: 'Theo phòng ban', href: '/report/revenue/department?businessId=122623' },
      { text: 'Theo danh mục sản phẩm', href: '/report/revenue/category?businessId=122623' },
      { text: 'Theo danh mục nội bộ', href: '/report/revenue/internalcategory?businessId=122623' },
      { text: 'Theo sản phẩm', href: '/report/revenue/product?businessId=122623' },
      { text: 'Theo nhà cung cấp', href: '/report/revenue/supplier?businessId=122623' },
      { text: 'Theo khách hàng', href: '/report/revenue/customer?businessId=122623' },
      { text: 'Tỷ suất doanh thu / tồn kho', href: '/report/revenue/inventoryrate?businessId=122623' },
      { text: 'Theo kênh bán', href: '/report/order/salechannel?businessId=122623' },
      { text: 'Đơn tạo', href: '/report/order/index?businessId=122623' },
      { text: 'Đơn thành công', href: '/report/order/success?businessId=122623' },
      { text: 'Theo giá trị đơn hàng', href: '/report/order/value?businessId=122623' },
      { text: 'Theo danh mục sản phẩm', href: '/report/order/category?businessId=122623' },
      { text: 'Theo sản phẩm', href: '/report/order/product?businessId=122623' },
      { text: 'Theo trạng thái', href: '/report/order/status?businessId=122623' },
      { text: 'Theo địa chỉ', href: '/report/order/location?businessId=122623' },
      { text: 'Lý do xử lý đơn hàng', href: '/report/order/cancel?businessId=122623' },
      { text: 'Nhân viên xử lý', href: '/report/order/create?businessId=122623' },
      { text: 'Theo quảng cáo', href: '/report/order/utm?businessId=122623' },
      { text: 'Tiền đối soát', href: '/report/order/verifyandtransfer?businessId=122623' },
      { text: 'Theo hãng vận chuyển', href: '/report/order/carrier?businessId=122623' },
      { text: 'Tổng quan', href: '/report/retail/index?businessId=122623' },
      { text: 'Theo nguồn khách hàng', href: '/report/retail/trafficsource?businessId=122623' },
      { text: 'Theo nhân viên', href: '/report/retail/cashier?businessId=122623' },
      { text: 'Theo cửa hàng', href: '/report/retail/depot?businessId=122623' },
      { text: 'Chi tiết quẹt thẻ', href: '/report/retail/creditmoney?businessId=122623' },
      { text: 'Theo giá trị hóa đơn', href: '/report/retail/billvalue?businessId=122623' },
      { text: 'Báo cáo tỷ lệ hóa đơn/ khách vào cửa hàng', href: '/report/retail/customerbillrate?businessId=122623' },
      { text: 'Báo cáo kết ca', href: '/report/retail/workshift?businessId=122623' },
      { text: 'Tổng quan', href: '/report/wholesale/index?businessId=122623' },
      { text: 'Theo nhân viên bán hàng', href: '/report/wholesale/storesale?businessId=122623' },
      { text: 'Xuất nhập tồn theo sản phẩm', href: '/report/inventory/index?businessId=122623' },
      { text: 'Chi tiết sản phẩm XNK', href: '/report/inventory/imex?businessId=122623' },
      { text: 'Tổng XNK', href: '/report/inventory/imextotal?businessId=122623' },
      { text: 'Tổng XNK theo cửa hàng', href: '/report/inventory/imexdepot?businessId=122623' },
      { text: 'Theo nhà cung cấp', href: '/report/inventory/supplier2?businessId=122623' },
      { text: 'Danh mục sản phẩm', href: '/report/inventory/category?businessId=122623' },
      { text: 'Số lượng hàng tồn kho', href: '/report/inventory/eachdepot?businessId=122623' },
      { text: 'Chuyển kho chưa xác nhận', href: '/report/inventory/transfer?businessId=122623' },
      { text: 'Theo trạng thái từng cửa hàng', href: '/report/inventory/depotinventorystatus?businessId=122623' },
      { text: 'Theo trạng thái từng sản phẩm', href: '/report/inventory/productinventorystatus?businessId=122623' },
      { text: 'Theo lô hàng', href: '/report/inventory/productbatchs?businessId=122623' },
      { text: 'Chuyển kho theo sản phẩm', href: '/report/inventory/producttransfer?businessId=122623' },
      { text: 'Bán chạy nhất', href: '/report/product/index?businessId=122623' },
      { text: 'Bán chạy theo cửa hàng', href: '/report/product/depot?businessId=122623' },
      { text: 'Tốc độ bán hàng', href: '/report/product/salespeed?businessId=122623' },
      { text: 'Theo kênh bán', href: '/report/product/salechannel?businessId=122623' },
      { text: 'Theo danh mục và cửa hàng', href: '/report/product/categorydetail?businessId=122623' },
      { text: 'Theo khoảng giá', href: '/report/product/value?businessId=122623' },
      { text: 'Theo ngày', href: '/report/product/date?businessId=122623' },
      { text: 'Bán hàng theo IMEI', href: '/report/product/salebyimei?businessId=122623' },
      { text: 'Theo thuộc tính', href: '/report/product/attribute?businessId=122623' },
      { text: 'Tổng hợp thu chi theo cửa hàng', href: '/accounting/report/cash?businessId=122623' },
      { text: 'Tổng hợp theo tài khoản', href: '/accounting/report/account?businessId=122623' },
      { text: 'Tổng hợp tiền bán lẻ hàng ngày theo cửa hàng', href: '/accounting/report/money?businessId=122623' },
      { text: 'Tổng hợp thu chi theo ngày', href: '/accounting/report/cashbook?businessId=122623' },
      { text: 'Tổng hợp kết quả kinh doanh', href: '/accounting/report/businessresult?businessId=122623' },
      { text: 'Bảng cân đối kế toán', href: '/accounting/report/balancesheet?businessId=122623' },
      { text: 'Tổng quan', href: '/report/customer/index?businessId=122623' },
      { text: 'Theo sản phẩm', href: '/report/customer/product?businessId=122623' },
      { text: 'Tỷ lệ khách quay lại', href: '/report/customer/total?businessId=122623' },
      { text: 'Cấp độ khách hàng', href: '/report/customer/level?businessId=122623' },
      { text: 'Nhóm khách hàng', href: '/report/customer/group?businessId=122623' },
      { text: 'Khách hàng tạo mới theo cửa hàng', href: '/report/customer/createnew?businessId=122623' },
      { text: 'Chu kỳ mua hàng', href: '/report/customer/frequencybought?businessId=122623' },
      { text: 'Sinh nhật khách hàng', href: '/report/customer/birthday?businessId=122623' },
      { text: 'Tỉ lệ với doanh thu', href: '/report/promotion/discountrate?businessId=122623' },
      { text: 'Quà tặng theo sản phẩm', href: '/report/promotion/productgift?businessId=122623' },
      { text: 'Theo sản phẩm', href: '/report/promotion/productdiscountrate?businessId=122623' },
      { text: 'Quà tặng theo cửa hàng', href: '/report/promotion/bonusbydepot?businessId=122623' },
      { text: 'Doanh thu theo bảng giá', href: '/report/promotion/pricelist?businessId=122623' },
      { text: 'Tin gửi theo ngày', href: '/report/zalo/historydate?businessId=122623' },
      { text: 'Tin gửi theo mẫu', href: '/report/zalo/template?businessId=122623' },
      { text: 'Đánh giá của khách hàng', href: '/report/zalo/rating?businessId=122623' },
      { text: 'Tin gửi theo ngày', href: '/report/sms/date?businessId=122623' },
    ]
  },
  {
    title: 'Sản phẩm & Kho hàng',
    items: [
      { text: 'Sản phẩm', href: '/product/item/index?businessId=122623' },
      { text: 'Thương hiệu', href: '/product/brand/index?businessId=122623' },
      { text: 'Lô sản phẩm', href: '/product/batch/index?businessId=122623' },
      { text: 'Thời gian lưu kho', href: '/product/item/storagetime?businessId=122623' },
      { text: 'Tồn kho', href: '/product/item/inventory?businessId=122623' },
      { text: 'Danh mục', href: '/product/category/index?businessId=122623' },
      { text: 'Thuộc tính', href: '/product/variant/index?businessId=122623' },
      { text: 'Nhà cung cấp', href: '/supplier/manage/index?businessId=122623' },
      { text: 'Xuất nhập kho', href: '/inventory/bill/index?businessId=122623' },
      { text: 'Chuyển kho', href: '/inventory/transfer/index?businessId=122623' },
      { text: 'Kiểm kho', href: '/inventory/check/index?businessId=122623' },
      { text: 'Phiếu nháp', href: '/inventory/requirement/bill?businessId=122623' },
      { text: 'Hạn mức tồn kho', href: '/inventory/archive/index?businessId=122623' },
      { text: 'Vị trí sản phẩm', href: '/inventory/position/index?businessId=122623' },
      { text: 'Danh mục vị trí', href: '/inventory/position/category?businessId=122623' },
      { text: 'HĐXN vị trí', href: '/inventory/position/bill?businessId=122623' },
      { text: 'Sản phẩm xuất nhập vị trí', href: '/inventory/position/imex?businessId=122623' },
      { text: 'Dự báo nhập hàng', href: '/inventory/forecasting/movingaverage?businessId=122623' },
      { text: 'Tổng công ty', href: '/inventory/product/companyavailable?businessId=122623' },
      { text: 'Lịch sử sửa xóa', href: '/inventory/log/imexbill?businessId=122623' },
    ]
  },
  {
    title: 'Bán hàng & Đơn hàng',
    items: [
      { text: 'Thêm gói sản phẩm', href: '/pos/bill/addpackage?businessId=122623' },
      { text: 'Bung gói sản phẩm', href: '/pos/bill/extractpackage?businessId=122623' },
      { text: 'Tìm hóa đơn', href: '/pos/bill/lookup?businessId=122623' },
      { text: 'Bán lẻ', href: '/pos/bill/index?businessId=122623' },
      { text: 'Bán sỉ', href: '/pos/bill/wholesale?businessId=122623' },
      { text: 'Hóa đơn điện tử', href: '/pos/invoice/index?businessId=122623' },
      { text: 'Trả hàng', href: '/pos/return/index?businessId=122623' },
      { text: 'Nợ quà tặng', href: '/pos/debt/bill?businessId=122623' },
      { text: 'Đơn hàng', href: '/order/manage/index?businessId=122623' },
      { text: 'Đơn trùng', href: '/order/manage/checkduplicate?businessId=122623' },
      { text: 'Đóng gói', href: '/order/manage/packing?businessId=122623' },
      { text: 'Biên bản bàn giao', href: '/shipping/handover/index?businessId=122623' },
      { text: 'Chờ gửi vận chuyển', href: '/order/manage/sendingcarrier?businessId=122623' },
      { text: 'Khiếu nại', href: '/order/manage/complain?businessId=122623' },
      { text: 'Đơn gửi qua Nhanh', href: '/order/payment/index?businessId=122623' },
      { text: 'Đơn tự kết nối', href: '/order/manage/payment?businessId=122623' },
      { text: 'Lịch sử sửa xóa', href: '/order/manage/deleted?businessId=122623' },
    ]
  },
  {
    title: 'Khách hàng & Đối tác',
    items: [
      { text: 'Danh sách khách hàng', href: '/customer/code/customerlist?businessId=122623' },
      { text: 'Thẻ khách hàng', href: '/customer/code/index?businessId=122623' },
      { text: 'Chăm sóc khách hàng', href: '/customer/care/index?businessId=122623' },
      { text: 'Cấp độ', href: '/customer/store/level?businessId=122623' },
      { text: 'Nhóm khách hàng', href: '/customer/group/index?businessId=122623' },
      { text: 'Hình thức chăm sóc', href: '/customer/type/index?businessId=122623' },
      { text: 'Lý do chăm sóc', href: '/customer/reason/index?businessId=122623' },
      { text: 'Like sản phẩm', href: '/social/like/index?businessId=122623' },
    ]
  },
  {
    title: 'Kế toán & Tài chính',
    items: [
      { text: 'Cài đặt', href: '/invoice/setting/index?businessId=122623' },
      { text: 'Hóa đơn', href: '/invoice/bill/index?businessId=122623' },
      { text: 'Thu chi tiền mặt', href: '/accounting/transaction/cash?businessId=122623' },
      { text: 'Thu chi ngân hàng', href: '/accounting/transaction/bank?businessId=122623' },
      { text: 'Tổng hợp thu chi', href: '/accounting/transaction/cashbook?businessId=122623' },
      { text: 'Sàn TMĐT', href: '/accounting/debts/merchant?businessId=122623' },
      { text: 'Nhân viên bán hàng', href: '/accounting/debts/salemandate?businessId=122623' },
      { text: 'Dịch vụ trả góp', href: '/accounting/debts/installment?businessId=122623' },
      { text: 'Trả góp theo ngày', href: '/accounting/debts/item?businessId=122623' },
      { text: 'Công nợ theo đầu tài khoản', href: '/accounting/debts/byaccount?businessId=122623' },
      { text: 'Nhập công nợ đầu kỳ', href: '/accounting/debts/add?businessId=122623' },
      { text: 'Bút toán', href: '/accounting/transaction/index?businessId=122623' },
      { text: 'Phát sinh đối ứng', href: '/accounting/transaction/reciprocalaccount?businessId=122623' },
      { text: 'Nhật ký chung', href: '/accounting/transaction/logbook?businessId=122623' },
      { text: 'Thu hộ trả góp', href: '/accounting/transaction/installments?businessId=122623' },
      { text: 'Lịch sử', href: '/accounting/transaction/logs?businessId=122623' },
      { text: 'Tài khoản kế toán', href: '/accounting/account/index?businessId=122623' },
      { text: 'Dịch vụ trả góp', href: '/accounting/contact/index?businessId=122623' },
    ]
  },
  {
    title: 'Kênh bán (TMĐT)',
    items: [
      { text: 'Báo cáo tài chính', href: '/ecommerce/finance/dashboard?businessId=122623' },
      { text: 'Đối soát COD', href: '/ecommerce/manage/index?businessId=122623' },
      { text: 'Trả hàng hoàn tiền', href: '/ecommerce/manage/return?businessId=122623' },
      { text: 'Shopee - Sản phẩm', href: '/ecommerce/shopee/product?businessId=122623' },
      { text: 'TikTok - Sản phẩm', href: '/ecommerce/tiktok/product?businessId=122623' },
      { text: 'Lazada - Sản phẩm', href: '/ecommerce/lazada/product?businessId=122623' },
    ]
  },
  {
    title: 'Cài đặt & Khác',
    items: [
      { text: 'Thông báo hệ thống', href: '/thong-bao-lich-bao-tri-server-dip-tet-nguyen-dan-2026-an917.html' },
      { text: 'Cài đặt', href: '/website/content/setting?businessId=122623' },
      { text: 'Tag', href: '/website/content/tags?businessId=122623' },
      { text: 'Album', href: '/website/album/index?businessId=122623' },
      { text: 'Link điều hướng', href: '/website/redirectlink/index?businessId=122623' },
      { text: 'Chiết khấu', href: '/promotion/setting/discount?businessId=122623' },
      { text: 'Thiết lập bảng giá', href: '/promotion/setting/pricelist?businessId=122623' },
      { text: 'Tích điểm', href: '/promotion/setting/point?businessId=122623' },
      { text: 'Mã giảm giá', href: '/promotion/setting/coupon?businessId=122623' },
      { text: 'Quà tặng', href: '/promotion/setting/gift?businessId=122623' },
      { text: 'Hoa hồng bán hàng', href: '/promotion/setting/commission?businessId=122623' },
      { text: 'Nhân viên', href: '/store/user/index?businessId=122623' },
      { text: 'Cài đặt chung', href: '/setting/store/index?businessId=122623' },
      { text: 'Bán hàng và XNK', href: '/setting/store/sale?businessId=122623' },
      { text: 'Cài đặt nhãn', href: '/setting/store/labels?businessId=122623' },
      { text: 'Mẫu in', href: '/store/template/design?businessId=122623' },
      { text: 'Gửi email', href: '/setting/email/index?businessId=122623' },
      { text: 'Thanh toán', href: '/setting/payment/index?businessId=122623' },
      { text: 'Chi nhánh', href: '/store/branch/index?businessId=122623' },
      { text: 'Hạn sử dụng', href: '/setting/expire/depot?businessId=122623' },
    ]
  }
];
